Update README with examples and links to feedback collection
unicode-org/message-format-wg pull request #308
Opened 2022-10-19 10:11 UTC by stasm

I'd like to improve the README so that:

* It tells a better story of what MessageFormat is.
* It showcases a few examples of the draft syntax.
* It points to the existing tech preview implementations.
* It redirects users who want to share feedback to appropriate forums.

2022-10-19 15:45 UTC, romulocintra approved these changes
Thank you @stasm  for this PR

2022-10-19 21:26 UTC, echeran requested changes
Flipping the review bit so that we don't merge until Mark's comment is addressed, at least.  We shouldn't knowingly be precise on things that are in reality TBD / done differently.

2022-10-20 07:27 UTC, eemeli approved these changes

2022-10-20 07:27 UTC, eemeli commented on README.md
> +The Message Format Working Group (MFWG) is tasked with developing an industry standard for the representation of localizable message strings to be a successor to [ICU MessageFormat](https://unicode-o
Not necessarily requiring action, but seeing what's different here would've been easier if this file used [semantic line breaks](https://sembr.org/).

2022-10-20 16:06 UTC, echeran approved these changes

2022-10-20 23:59 UTC, echeran reviewed
Based on offline discussion with @stasm and @eemeli, I'm suggesting changing the "2.0" to "2" so that we don't give the impression that our current working specification has the formalism or completion that an unqualified semver like "2.0" implies.  Especially when measuring progress in relation to the CLDR-TC guidance on the scope of our goals for what 2.0 entails.

optional: the specification's docs on [syntax](https://github.com/unicode-org/message-format-wg/blob/main/spec/syntax.md) and [formatting](https://github.com/unicode-org/message-format-wg/blob/main/spec/formatting.md) both include "DRAFT" alongside the title, but if you agree with these changes, then it would be good to update those instances of "2.0" to "2", too.

2022-10-20 23:59 UTC, echeran commented on README.md
> +## MessageFormat 2.0 Draft Syntax
```suggestion
## MessageFormat 2 Draft Syntax
```

2022-10-20 23:59 UTC, echeran commented on README.md
> +* Java: [`com.ibm.icu.message2`](https://unicode-org.github.io/icu-docs/apidoc/dev/icu4j/index.html?com/ibm/icu/message2/package-summary.html), part of ICU 72 released in October 2022, is a _tech pre
```suggestion
* Java: [`com.ibm.icu.message2`](https://unicode-org.github.io/icu-docs/apidoc/dev/icu4j/index.html?com/ibm/icu/message2/package-summary.html), part of ICU 72 released in October 2022, is a _tech preview_ implementation of the MessageFormat 2 syntax, together with a formatting API.
```

2022-10-20 23:59 UTC, echeran commented on README.md
> +* JavaScript: [`messageformat`](https://github.com/messageformat/messageformat/tree/master/packages/mf2-messageformat) 4.0 implements the MessageFormat 2.0 syntax, together with a polyfill of the run
```suggestion
* JavaScript: [`messageformat`](https://github.com/messageformat/messageformat/tree/master/packages/mf2-messageformat) 4.0 implements the MessageFormat 2 syntax, together with a polyfill of the runtime API proposed for ECMA-402.
```

2022-10-21 06:22 UTC, stasm commented
> optional: the specification's docs on [syntax](https://github.com/unicode-org/message-format-wg/blob/main/spec/syntax.md) and [formatting](https://github.com/unicode-org/message-format-wg/blob/main/spec/formatting.md) both include "DRAFT" alongside the title, but if you agree with these changes, then it would be good to update those instances of "2.0" to "2", too.

I agree with the direction of this change across the repo, but I think we should do it in a separate PR.

2022-10-21 19:39 UTC, echeran commented
> I agree with the direction of this change across the repo, but I think we should do it in a separate PR.

Sounds good.

2022-10-24 16:51 UTC, merged