Add proposed/accepted status to design docs
unicode-org/message-format-wg pull request #461
Opened 2023-08-28 21:02 UTC by eemeli

We should track and signal the status of a design document, so that we can iterate on them across multiple PRs. To keep it simple, we probably don't need more than two statuses to start with, "proposed" and "accepted".

CC @ryzokuken, who also has a design doc PR in flight.

2023-08-29 14:57 UTC, aphillips requested changes
But otherwise ready...

2023-08-29 14:57 UTC, aphillips commented on exploration/0000-design-proposal-template.md
> +_Use either **Proposed** or **Accepted** as the status._
I would say:

```suggestion
_Use the status **Proposed** when creating a design proposal._
_The status will be changed to **Accepted** when the design proposal is accepted as working group consensus._
_The status will be changed to **Rejected** if the design proposal ultimately is not adopted by the working group._

2023-08-29 15:06 UTC, eemeli commented
Requesting fast-tracking.

2023-08-29 16:11 UTC, stasm commented
In my mind, a design doc would only be merged into `main` when it's accepted. Furthermore, I think that splitting a design doc into multiple PRs may again make it more difficult to track the discussion around it. Instead, I think we should encourage long-lived PRs and multiple rounds of reviews.

2023-08-29 19:16 UTC, ryzokuken approved these changes

2023-08-30 08:53 UTC, eemeli commented
@stasm Could you review #458, as that's effectively the prototypical reason for this change?

It's currently at 35 comments in 13 threads of review comments, most of which are hidden as resolved. If we don't make this change, we won't be able to merge the PR until all expression attribute design questions are answered, including e.g. whether it's the proper vessel for communicating "open" vs. "closed" concepts which have not yet been mentioned at all.

2023-09-02 14:49 UTC, aphillips approved these changes

2023-09-02 14:49 UTC, merged