Describe registry use and conformance
unicode-org/message-format-wg pull request #563
Opened 2023-12-12 18:58 UTC by aphillips

Addresses my comments in #561

2023-12-12 19:11 UTC, eemeli requested changes

2023-12-12 19:11 UTC, eemeli commented on spec/registry.md
> +all of the _selectors_ and _functions_ described in the default registry,
Should reword slightly, as _functions_ includes selectors.

```suggestion
To be conformant with MessageFormat 2.0, an implementation MUST implement
all of the formatting and selection _functions_ described in the default registry,
```

2023-12-12 19:11 UTC, eemeli commented on spec/registry.md
> +signatures for _selectors_ and _functions_ that all implementations of MessageFormat 2.0
```suggestion
signatures for _functions_ that all implementations of MessageFormat 2.0
```

2023-12-12 19:11 UTC, eemeli commented on spec/registry.md
> +as expected outputs.
Actually, the registry does not (at least currently) define expected outputs.

```suggestion
The MessageFormat 2.0 Registry was created to describe
the core set of formatting and selection _functions_,
including _operands_, _options_, and _option_ values.
```

2023-12-12 19:11 UTC, eemeli commented on spec/registry.md
> +regardless of programming language or runtime environment.
I don't think we can _ensure_ interop, but we can at least try.

```suggestion
The goal is to enable message interoperability between implementations,
regardless of programming language or runtime environment.
```

2023-12-12 19:11 UTC, eemeli commented on spec/registry.md
> +when moving between platforms
```suggestion
This ensures that developers do not have to relearn core MessageFormat syntax
and functionality when moving between platforms
```

2023-12-12 19:11 UTC, eemeli commented on spec/registry.md
> +The registry provides a machine-readable description of _selectors_ and _functions_
```suggestion
The registry provides a machine-readable description of _functions_
```

2023-12-12 19:26 UTC, eemeli approved these changes

2023-12-18 17:39 UTC, mihnita approved these changes

2023-12-18 17:40 UTC, merged