Remove tests that rely on nonexistent bad-option error
unicode-org/message-format-wg pull request #740
Opened 2024-03-19 19:13 UTC by catamorphism

I suggest we remove these two tests for now, because the property that they are testing is actually underspecified. There is nothing in errors.md corresponding to the `bad-option` error, and what's more, the spec doesn't require `:number` to signal an error for a non-integer `minimumFractionDigits` value.

I filed #738 and #739 to clarify those issues in the spec, but I think the tests should be removed in the meantime, and re-added once the behavior is fully specified.

2024-03-19 19:38 UTC, aphillips commented
I think this would be a mistake. I agree that there is no specific `bad-option` error. I think we should fix registry.md for some of the cases you point out. I think that number formatting is so common that these options should be well-clarified now--and that there will be general agreement about how to do that. I think these tests should be retained.

2024-03-19 20:02 UTC, aphillips commented
Note: I made #741 to (try to) address part of the gap. It doesn't mess with the `bad-option` problem.

2024-03-19 21:40 UTC, eemeli requested changes
I don't think these should be dropped. The right fix here would be to better define the behaviour for `:number minimumFractionDigits=foo`, which should indeed be considered an error.

2024-03-21 13:56 UTC, aphillips commented
I'm marking this for Monday's agenda. I used `resolve-candidate` because at least two of us feel that this shouldn't go in, but that doesn't mean the WG won't feel differently.

2024-03-25 16:45 UTC, closed without merging

2024-03-25 18:07 UTC, aphillips commented
In the 2024-03-25 call we agreed not to merge this.