Add tests for :currency
unicode-org/message-format-wg pull request #940
Opened 2024-11-16 13:29 UTC by eemeli

These probably should've been a part of #915.

2024-11-16 14:01 UTC, aphillips requested changes

2024-11-16 14:52 UTC, aphillips commented on test/tests/functions/currency.json
> +      "expErrors": true
bad operand?

2024-11-16 14:52 UTC, aphillips approved these changes

2024-11-16 15:46 UTC, eemeli commented on test/tests/functions/currency.json
> +      "expErrors": true
Yes.
```suggestion
      "expErrors": [{ "type": "bad-operand" }]
```

2024-11-16 16:08 UTC, aphillips approved these changes

2024-11-17 15:03 UTC, aphillips commented
I need one more review to merge.

2024-11-18 18:02 UTC, merged