Add calendar and numberingSystem options to date/time
unicode-org/message-format-wg pull request #949
Opened 2024-11-19 01:04 UTC by macchiati

This is as per the discussion in the WG, separating them out from https://github.com/unicode-org/message-format-wg/pull/911

Two changes from that:
1. Used RECOMMENDED instead of Optional, as per https://github.com/unicode-org/message-format-wg/pull/946
2. I noticed also there that RECOMMENDED needs a maturity status, so added a placeholder for that.

2024-11-19 01:13 UTC, aphillips commented
I resolved the conflict. In doing so, I reordered the proposed options below the REQUIRED one and rephrased the text slightly to take advantage of the fact that REQUIRED and RECOMMENDED are 2119 keywords. Please have a look.

2024-11-19 10:16 UTC, eemeli requested changes
At least the `calendar` and `numberingSystem` mentions should also be removed from this note: https://github.com/unicode-org/message-format-wg/blob/960f8003cc9d725b4b473877e3391abf101aafe4/spec/registry.md?plain=1#L952-L964

2024-11-19 15:03 UTC, aphillips commented
@eemeli I will make a separate PR to remove the note.

2024-11-19 17:01 UTC, merged

2024-11-21 09:32 UTC, mihnita reviewed
For some reason I can review, but can't approve.
My only button is "Submit review"

So: approved